//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityAdmissionApplicationProcessingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id { get; set; }
         [Required(ErrorMessage = "Enter Your User Name")]
        public string UserName { get; set; }
         [Required(ErrorMessage = "Enter Your Password")]
        public string Password { get; set; }
    }
}
